services:
  revbreakbot:
    build: .
    image: deltabot:latest
    container_name: revbreakbot
    restart: always
    env_file:
      - .env.revbreak
    volumes:
      - ./state:/app/state
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    stop_grace_period: 30s
